version: '3.7'

services:
  db:
    container_name: classtimes-db
    restart: unless-stopped
    env_file: .env
    image: mongo
    environment:
      # - ME_CONFIG_MONGODB_ADMINUSERNAME=$MONGO_USER
      # - ME_CONFIG_MONGODB_ADMINPASSWORD=$MONGO_PASSWORD
      - ME_CONFIG_MONGODB_URL=$MONGODB_URL
    ports:
      - $MONGODB_PORT:27017
    networks:
      - api

networks:
  api:
